### ISSUE TITLE
Not wipe out DOM when changing values?

### ISSUE THREAD

**Issue by iest** [chenglou/react-radio-group#12]
Firstly, great idea! Love it.

However, when changing values, React completely wipes out the DOM inside the `radio` components. This is not ideal when wanting to animate the radio buttons after being checked etc.

The best I could come up with (while still keeping the same pattern) was to use `defaultChecked` on the inputs instead of `checked`, and make `shouldComponentUpdate` inside the parent return `false`. Effectively making it an "uncontrolled" component.

Feel free to close this issue as it's kinda solved — I was just wondering if you had any thoughts how this could be done a little cleaner?

**Comment by chenglou** [comment]
Ah, that's because I create a new react class, so the diffing algorithm does the equality check and resets the dom elements. Would #11 solve this problem?

**Comment by nkbt** [comment]
use `React.cloneElement`

**Comment by iest** [comment]
Ahh... yes I guess #11 is sort of the same issue.

@nkbt how/where would you use `cloneElement`?

**Comment by nkbt** [comment]
@iest it should be part of library. Instead of rendering same element again and again it could be created independently and then you can clone it like

```js
  render() {
    return React.cloneElement(React.Children.only(this.props.children), additionalProps);
  }
```

**Comment by nkbt** [comment]
This is a good way to create wrapper-components that do not add their own dom as well.

**Comment by nkbt** [comment]
So it could be something like

```js
{children && children(React.cloneElement(CachedRadioElement, {name, selectedValue, onChange}))}
```

And of course we need `CachedRadioElement` which should be rendered separately, once.

Probable cached in `this.CachedRadioElement` and created when component is mounted.

**Comment by chenglou** [comment]
How are you gonna cache the function handler if it's inlined in render?

**Comment by nkbt** [comment]
I can give it a shot and do PR if successful =).

**Comment by nkbt** [comment]
Actually right, it is a problem. When you render an element you cannot use it as `<Radio>` anymore, only as {Radio}.

On the other side if you create class then it is actually a new class every time and it will mount every any of props-arguments are changed.

I made one PR with breaking changes to show how it can be done. Will dig a bit more though. I think I have another idea.

**Comment by nkbt** [comment]
Okay... here is another dirty hack to make it work with memoize, see #14

**Comment by gkop** [comment]
I am observing now with react-radio-group because the browser focus state resets when choosing a radio option, breaking a11y for my users. @nkbt I wanted to check out your PR https://github.com/chenglou/react-radio-group/pull/13 hoping that this would also my a11y issue, but it doesn't have the lib/ build directory, and it conflicts with master now anyway :/

**Comment by nkbt** [comment]
@gkop I'll rebase it later today. It should fix the issue.

@chenglou I know you are now focused on other things, but what do you reckon on #13 and #14

**Comment by chenglou** [comment]
Sorry, haven't been paying attention to this enough. What are the breaking changes?

**Comment by nkbt** [comment]
@chenglou #13 changes API, #14 does not have any, but code smells. I put as much comments there as possible

**Comment by gkop** [comment]
@nkbt how can I test your code? When I install the released version from npm repositories, the lib/ directory is present. When I install yours by giving npm "nkbt/react-radio-group#new-api", the lib/ directory is not present.

**Comment by nkbt** [comment]
@gkop I think you can just checkout repo, switch to a branch and run test example.

Alternatively you should:
1. checkout my branch (clone)
2. run build
3. do install from fs: `npm install ~/nkbt/react-radio-group`


The problem you not having `lib` is I believe a lack of `prepublish` script. Build is done in `prerelease`, which is not really correct.

**Comment by gkop** [comment]
Thanks for the help understanding npm @nkbt ! :) that makes sense. Meanwhile I have switched to using https://github.com/zippyui/react-radio which solved my a11y issue and is otherwise quite similar to this repo I think.

**Comment by chenglou** [comment]
@nkbt giving you push rights to this repo. We should try the new stateless function components for this.

**Comment by nkbt** [comment]
Thanks, I'll give a shot asap.

**Comment by bsr203** [comment]
hi @nkbt any plan for merging or using function component? thanks.

**Comment by nkbt** [comment]
Both solutions i submitted are not really perfect. I am not sure. Would
prefer to find better one

**Comment by danielberndt** [comment]
While the function-as-a-child idea is very charming and I've used it widely within my apps, I again and again get into issues because of this exact issue of recreating classes for each render.

Usually I refactor this via using `context`. I.e `<RadioGroup>` creates a context and `<Radio>` will require this context to work.

Here's a solution working with context could look like for the end user:

```
import {RadioGroup, Radio} from "react-radio-group";

...

render() {
  return (
    <form ...>
      <RadioGroup name="fruit" selectedValue={this.state.selectedValue} onChange={this.handleChange}>
        <label><Radio value="apple"/> Apple</label>
        ...
      </RadioGroup>
    </form>
  );
}
```
I realise it's quite a substantial breaking change, but not having to use the function-as-a-child syntax will probably make it easier for newcomers to use, plus fixing this issue would be straight forward in that case.

I'm happy to do a PR if you're interested in pursuing this idea further

**Comment by nkbt** [comment]
That is interesting idea. In general I am quite against context, but in this case it feels like a pretty great solution! @chenglou what do you reckon?

**Comment by chenglou** [comment]
Thanks for the ping. Commented on the PR.

**Comment by chenglou** [comment]
Alright, so the PR is merged. Please try master (67a2bcdc7f3d0c8cb4d7762f82558d75c9592ea9). Things should work now. @danielberndt and @nkbt can publish this =).
