### ISSUE TITLE
Please support React 0.14

### ISSUE THREAD

**Issue by dminkovsky** [chenglou/react-radio-group#20]
I think you just need to change the dependency information in package.json.

I wouldn't post this issue, but the peerDependency is preventing me from using it with 0.14.

Thank you.

**Comment by dminkovsky** [comment]
I've seen:

```
"react": ">=0.13.3 || ^0.14.0-rc1"     
```

**Comment by nkbt** [comment]
@dminkovsky fancy doing a PR?

**Comment by dminkovsky** [comment]
Sure thing https://github.com/chenglou/react-radio-group/pull/21

**Comment by dminkovsky** [comment]
Not necessary with 0.14 out.
