### ISSUE TITLE
Breaking the whole render function

### ISSUE THREAD

**Issue by subhojit777** [chenglou/react-radio-group#31]
I am trying to render group of radio buttons using this component. This is what I wrote inside `render()`:
```javascript
      <div className="form-wrapper">
        {alert}
        <form onSubmit={this.handlePostAnswer}>
          <h3 className="question">{this.props.question.question}</h3>
          <div className="options-wrapper well" onClick={this.handleOptionChange}>
            <RadioGroup name="options" onChange={this.handleOptionChange}>
              {Radio => (
                <div className="radio">
                  <label>
                    <Radio value="radio1" /> Radio 1
                  </label>
                </div>
                <div className="radio">
                  <label>
                    <Radio value="radio2" /> Radio 2
                  </label>
                </div>
              )}
            </RadioGroup>
          </div>
          <button type="submit" className="btn btn-primary">Submit</button>
        </form>
      </div>
```

This breaks the whole page, I mean it does not renders anything. The state and props are all fine - I checked. There is even no errors/warnings in logs.

I have even tried rendering a simple radio button using this `<Radio name="something" /> Some radio`, even this breaks the whole render operation.

Not sure what I am doing wrong, any help would be appreciated. Thanks.

**Comment by dandean** [comment]
The content of this must be wrapped in a single element:

```js
{Radio => (
  <div>
     ...
  </div>
)}
```

You have two elements in the top level of that.

**Comment by subhojit777** [comment]
Still not working

```jsx
      <div className="form-wrapper">
        {alert}
        <form onSubmit={this.handlePostAnswer}>
          <h3 className="question">{this.props.question.question}</h3>
          {/* @TODO use https://github.com/chenglou/react-radio-group */}
          <div className="options-wrapper well" onClick={this.handleOptionChange}>
            <RadioGroup onChange={this.handleOptionChange}>
              {Radio => (
                <div>
                  <Radio value="radio1" /> Radio 1
                  <Radio value="radio2" /> Radio 2
                </div>
              )}
            </RadioGroup>
          </div>
          <button type="submit" className="btn btn-primary">Submit</button>
        </form>
      </div>
```

**Comment by subhojit777** [comment]
BTW I am writing the code in ES6 format. I don't think that might be the issue.

**Comment by bvn13** [comment]
I have the same problem.
Using ES6.

**Comment by danielberndt** [comment]
The API was changed quite a lot with v3.0.0. So you now can write your code like this:

```
import {RadioGroup, Radio} from "react-radio-group";

...

<RadioGroup name="options" onChange={this.handleOptionChange}>
  <div className="radio">
    <label>
      <Radio value="radio1" /> Radio 1
    </label>
  </div>
  <div className="radio">
    <label>
      <Radio value="radio2" /> Radio 2
    </label>
  </div>
</RadioGroup>
```

Please let us know if there are any issues left with the new syntax. Otherwise I'm going to close this issue in the next couple of days :)

**Comment by kellyjanderson** [comment]
Using that code I am getting errors. Using ES6 style coding in current React.
<img width="1437" alt="screen shot 2016-06-29 at 5 43 38 pm" src="https://cloud.githubusercontent.com/assets/643583/16471272/3230f790-3e21-11e6-9df7-65efd1c7cfda.png">

**Comment by danielberndt** [comment]
which react-radio-group version are you using? v3.0.0 had a broken build, so please check if you're using v3.0.1

**Comment by kellyjanderson** [comment]
@danielberndt I am using "react-radio-group": "2.2.0",

**Comment by kellyjanderson** [comment]
Updated to 3.0.1 and it is rendering.

**Comment by subhojit777** [comment]
It is also working for me. Thanks.
