### ISSUE TITLE
React warning about propTypes

### ISSUE THREAD

**Issue by fraserxu** [chenglou/react-radio-group#41]
Hi there, I've noticed that the latest version(3.0.1) published to npm is still using `React.PropTypes` even though the source code has been updated.

I believe it's because the code is not build properly before publishing?

Here you can check from the code compiled on npm is still referring to React.

https://unpkg.com/react-radio-group@3.0.1

```js
var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var Radio = _react2['default'].createClass({
  displayName: 'Radio',

  contextTypes: {
    radioGroup: _react2['default'].PropTypes.object
  },

```

**Comment by nkbt** [comment]
Sorry not released yet

> --
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by fraserxu** [comment]
@nkbt @chenglou Any plan on release it?

**Comment by michaelryancaputo** [comment]
Would be happy to help get this released if necessary.

**Comment by chrisjpatty** [comment]
Same, would be happy yo help get this released if needed.

**Comment by basicdays** [comment]
I see the code fix was committed a month ago but not published yet. Are there any plans for the update to be released?

**Comment by chenglou** [comment]
Hello! Sorry for the delay. v3.0.2 has been released. Ping me if other issues pop up. Thanks!
